language: python

python:
  - "2.7"

script:
  - flake8 .

deploy:
  - provider: pypi
    distributions: sdist
    user: adrianmo
    password:
      secure: "V9x59v3rWu7lBb8yZxlrrzTAfK/o8eGyBJseNBS6mTgBmRBNWlTQ8uextypNrASoekhaNVAEc6up3aTqszAsMfjoMLMJ0e+JFxg38llPUuHUQ6FqPRxT7lg8mPIdw49Re/KVbKSVtXYvNaVjTi3zZLDLR4a+hrgdoY2VwQEKdlTYOykHJzFeHvZoWeOaTAPKxWo/bFQnghzmMPISCauIGmmVBMxKb1rbvxFU3sX/N2z2ehaxw0qeCY4Y62+2TqDL3oQUSAsywyaETvHUTmh9pR6TdR+WGFTtY2RKLyKru1AD39/2muQCYnw9tpJtMu7qouHLQhZR3gUaciYzr75vGkAx5AHDok4zILT1jGmB628TeJoWIjfUKAgAIjgn+G2PCBopjODHZDczLZtCv2ZV0q18JEzG2HWx0hS0OPmy1jJsWGSaF+0vOTgrRkHu4AdveNWlHjGpC15JscqPDzNIxEOgVMJvgzYCFtnDXE5xQ4EMUd+XSkEQojmjpGushgS1SG8Z2hyj0/EKh/o/sPYkiBfq1XjSKU23Cnjim8gp3YOKM45oRLJvmnmqgWJBUgL2Q4OpV1Da1qyEf4Zpa8huazcE8l8wM37OLfFrRmDbzkaE1qPcgT1/cYbUsovPAX+w4lagiMdHqbp8+v6grX5GjAyXu3KDsogx1hoVBY5bVuE="
    on:
      branch: master
      tags: true
  - provider: pypi
    distributions: sdist
    server: https://testpypi.python.org/pypi
    user: adrianmo
    password:
      secure: "QORdGsls9SFqAEsAkFKhodLiIjUXPIZpxYvBmWnrgfir3vIxwtmadOPJDL5SSoYhlOHS1GbQR45O9tmXmVPZj/eQO1p2ENlbZyAohZfeH4oV9iDSz/aNOteth0wC0Ds4Mf7Li5v32fD3C3I/MEA3Usddei+k865B8Qk19Q+Y6P+S/F/9LnHRAVg9HgJd8CKxaG2aPBRqki6rwBR4hNI56Onj1KSz5I2WF3rBt8UOgVA2nYA326yQHUTCaOm8y6CaFQsHPaDE0facnSlG99xbj++HfoLoru5WyRUyQCfrVJ0hRqwC2aJp3gJbyuRQANfQnSttLaFklIfhbuHHoXR9W0B0Gn3C1y04d0hmBa6h/dqzD+itOOEwdGs669njeg6Hv5x2r8IOuoNENXG6xFe7VU6ZpaIePm/NQ3ncSLJF1pdKStMcgnhp8jt/tVU7H9/4a95Hc63Rn6PvTF+4RB3R4Fcvl0QPbb7ZBe921COjsDANAB4/mu+utDLxb8H1dSHvGz+OThgoUD9MF1Lefgt3ut+i3lw4nJdxlu2ETPprV0KewOmoX9H0txN87vnnRhis+QYXdC7h1ezppq0hUg4173O1EvAYnfd/sPk+mQLZ+vYZPt+6yB00ack/tjh2cQc6FpghBXO7LEEDHGnHlFIQrnvbfbP67szvyvSM0d6DkQU="
    on:
      branch: master
      tags: false
